
package br.com.dijalmasilva.soap.hotel.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HotelService", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelService {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.dijalmasilva.soap.hotel.ws.Reserva
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findReservaById", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.FindReservaById")
    @ResponseWrapper(localName = "findReservaByIdResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.FindReservaByIdResponse")
    public Reserva findReservaById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns br.com.dijalmasilva.soap.hotel.ws.Hotel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editHotel", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.EditHotel")
    @ResponseWrapper(localName = "editHotelResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.EditHotelResponse")
    public Hotel editHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Hotel arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteHotel", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.DeleteHotel")
    @ResponseWrapper(localName = "deleteHotelResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.DeleteHotelResponse")
    public void deleteHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.dijalmasilva.soap.hotel.ws.Hotel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHotelById", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.FindHotelById")
    @ResponseWrapper(localName = "findHotelByIdResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.FindHotelByIdResponse")
    public Hotel findHotelById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveHotel", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.SaveHotel")
    @ResponseWrapper(localName = "saveHotelResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.SaveHotelResponse")
    public void saveHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        Hotel arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.dijalmasilva.soap.hotel.ws.Hotel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllHotel", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.FindAllHotel")
    @ResponseWrapper(localName = "findAllHotelResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.FindAllHotelResponse")
    public List<Hotel> findAllHotel();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteReserva", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.DeleteReserva")
    @ResponseWrapper(localName = "deleteReservaResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.DeleteReservaResponse")
    public void deleteReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.dijalmasilva.soap.hotel.ws.Reserva>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllReserva", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.FindAllReserva")
    @ResponseWrapper(localName = "findAllReservaResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.FindAllReservaResponse")
    public List<Reserva> findAllReserva();

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.dijalmasilva.soap.hotel.ws.Reserva
     * @throws ReservaException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveReserva", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.SaveReserva")
    @ResponseWrapper(localName = "saveReservaResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.SaveReservaResponse")
    public Reserva saveReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Reserva arg0)
        throws ReservaException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns br.com.dijalmasilva.soap.hotel.ws.Reserva
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editReserva", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.EditReserva")
    @ResponseWrapper(localName = "editReservaResponse", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.hotel.ws.EditReservaResponse")
    public Reserva editReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Reserva arg1);

}
