
package br.com.dijalmasilva.soap.hotel.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ReservaException", targetNamespace = "http://ws.hotel.soap.dijalmasilva.com.br/")
public class ReservaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ReservaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ReservaException_Exception(String message, ReservaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ReservaException_Exception(String message, ReservaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.dijalmasilva.soap.hotel.ws.ReservaException
     */
    public ReservaException getFaultInfo() {
        return faultInfo;
    }

}
