
package br.com.dijalmasilva.soap.passagem.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PassagemService", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PassagemService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns br.com.dijalmasilva.soap.passagem.ws.Passagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "edit", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.EditResponse")
    public Passagem edit(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Passagem arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.dijalmasilva.soap.passagem.ws.Passagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.FindByIdResponse")
    public Passagem findById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.dijalmasilva.soap.passagem.ws.Passagem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.FindAllResponse")
    public List<Passagem> findAll();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.dijalmasilva.soap.passagem.ws.Passagem
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", className = "br.com.dijalmasilva.soap.passagem.ws.SaveResponse")
    public Passagem save(
        @WebParam(name = "arg0", targetNamespace = "")
        Passagem arg0)
        throws Exception_Exception
    ;

}
