
package br.com.dijalmasilva.soap.passagem.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PassagemServiceService", targetNamespace = "http://ws.passagem.soap.dijalmasilva.com.br/", wsdlLocation = "http://localhost:8080/soap-passagem/PassagemServiceService?wsdl")
public class PassagemServiceService
    extends Service
{

    private final static URL PASSAGEMSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PASSAGEMSERVICESERVICE_EXCEPTION;
    private final static QName PASSAGEMSERVICESERVICE_QNAME = new QName("http://ws.passagem.soap.dijalmasilva.com.br/", "PassagemServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap-passagem/PassagemServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PASSAGEMSERVICESERVICE_WSDL_LOCATION = url;
        PASSAGEMSERVICESERVICE_EXCEPTION = e;
    }

    public PassagemServiceService() {
        super(__getWsdlLocation(), PASSAGEMSERVICESERVICE_QNAME);
    }

    public PassagemServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PassagemService
     */
    @WebEndpoint(name = "PassagemServicePort")
    public PassagemService getPassagemServicePort() {
        return super.getPort(new QName("http://ws.passagem.soap.dijalmasilva.com.br/", "PassagemServicePort"), PassagemService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PassagemService
     */
    @WebEndpoint(name = "PassagemServicePort")
    public PassagemService getPassagemServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.passagem.soap.dijalmasilva.com.br/", "PassagemServicePort"), PassagemService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PASSAGEMSERVICESERVICE_EXCEPTION!= null) {
            throw PASSAGEMSERVICESERVICE_EXCEPTION;
        }
        return PASSAGEMSERVICESERVICE_WSDL_LOCATION;
    }

}
